### PR TITLE
refactor card component with arrow fn

### PR DESCRIPTION
**Pull request by cenjennifer**
Small change refactoring `function` to `const/arrow function` commented by @hakimelek after this PR merge: https://github.com/pricelinelabs/design-system/pull/100

### CODE REVIEW

**Comment by jes708** [comment]
I'm having some trouble with the `Card` component.  I tried including it in a component, but then all of the component's tests fail as follows:

```TypeError: Cannot read property '0' of undefined

      at boxShadow (node_modules/pcln-design-system/dist/Card.js:29:43)
```


implemented as follows

```<Card mb={2} bg='white' boxShadowSize='md'>```

May be worth fixing in this PR if possible

**Comment by cenjennifer** [comment]
@jes708: Try passing in `theme={theme}` in your card component test. I think it is trying to reference the `boxShadows` array in theme

**Comment by jes708** [comment]
Thanks @cenjennifer, The ThemeProvider needed to be added as a wrapper in the tests.

**Comment by jes708** [comment]
Not too many people have been doing this, but it might be worth it to add a link to the `<Card>` documentation in `README.md`

**Pull request merged**
