### PR TITLE
feat: Added no underline for visited

### PR DESCRIPTION
**Pull request by jon06712**
Removing underlined link for visited state.

### CODE REVIEW

**Comment by jxnblk** [comment]
Thanks for the PR! Would you mind adding a little more context around this change? I'm not sure I understand why we'd want this to be the default behavior for links. Maybe someone from the design team can chime in

**Comment by BeniCheni** [comment]
Would like to have design rep. to review to weigh in the visited state of link & approve. cc Isaiah Miller.

**Comment by wesleymartin85** [comment]
I agree with Jackson, I need a little more understanding around the need for this and what brought about this request. In general I don’t think we should make this the default behavior.

**Comment by jon06712** [comment]
Well right now you have to write styles so the visited stated is not underlined. If everyone wants to write extra code all the time cool!

**Comment by lauradhahn** [comment]
Per design team, the underline shouldn’t be there for visited links. only active and possibly hover if needed.

**Comment by jxnblk** [comment]
So from my understanding, the behavior that @lauradhahn mentioned *is* the current behavior without this change. (see https://pricelinelabs.github.io/design-system/Link/) 

@jon06712 are you sure there isn't some other CSS that's affecting how links are styled in your app?

> Well right now you have to write styles so the visited stated is not underlined. If everyone wants to write extra code all the time cool!

As for this comment, since it's a React component, you should only need to do this once in your application. I'm not sure I understand the issue?

**Comment by jon06712** [comment]
I've had to add this class more than once as the default behavior gives an underline. Maybe this isnt the exact cause, I would have to dig further but I think I'll drop this though because its too much effort. its easier to overwrite when needed.

**Pull request closed without merging**
