### PR TITLE
adding Dot Icon to design system. Icon provided by Wilfred Morales

### PR DESCRIPTION
**Pull request by anuj-kapoor**

### CODE REVIEW

**Comment by BeniCheni** [comment]
Thanks @jes708. Ping/ @anuj-kapoor , can you check out what Jon observed? (I can still wait for this PR until later today to merge the approved PRs and publish for the week)

**Comment by anuj-kapoor** [comment]
Thanks @BeniCheni , The svg Icon was provided by Wilfred Morales, I can probably reach out to Wilfred or @wesleymartin85 , who may be able to look at it

**Comment by anuj-kapoor** [comment]
@BeniCheni @jes708 , I updated the svg with new file provided by Wesley. Please review when you get chance, Thanks!

**Comment by BeniCheni** [comment]
🎊 Landing in [1e93df3](https://github.com/pricelinelabs/design-system/commit/1e93df39ea3cbb52dae03ac3103d3eafcb473419).

**Pull request merged**
