### PR TITLE
chore(): remove DS_Store and update gitignore files

### PR DESCRIPTION
**Pull request by adhagam**

### CODE REVIEW

**Comment by BeniCheni** [comment]
Per @adhagam , closing this PR.

**Comment by BeniCheni** [comment]
Per @adhagam , re-opening as this PR seems valid.

**Comment by jes708** [comment]
Do the individual packages actually need `gitignore`s? Only the root is a git repository.

**Comment by adhagam** [comment]
> Do the individual packages actually need `gitignore` files? Only the root is a git repository.

Most of the projects inside packages/ already had .gitignore files. Its good to have the files if these projects are made standalone in future

**Pull request merged**
