### PR TITLE
Add contributor thumbnails to README.md

### PR DESCRIPTION
**Pull request by BeniCheni**
Add contributor thumbnails to `README.md` alphabetically:

- thumbnails link to profile photos
- Usernames below thumbnails link to provided website from profiles, or GitHub user page if no website provided

screen shot 2018-12-20 at 11 16 43 pm

### CODE REVIEW

**Comment by jxnblk** [comment]
This is great!

At first I thought you had pulled the CLI in, but looks like you did it manually? Might make sense to hook something like this up: https://www.npmjs.com/package/all-contributors-cli

**Comment by BeniCheni** [comment]
@jxnblk ,
> Might make sense to hook something like this up: https://www.npmjs.com/package/all-contributors-cli

I used `all-contributions-cli` to generate the template of the contributor thumbnails to start with, but ran into a CLI error
> API rate limit exceeded for 173.52.222.75. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

So I didn't want to introduce any toolset in doubt & dropped the toolset from this PR. Opened #427 to discuss the toolset & automation process for maintain contributor thumbnails.

**Comment by jxnblk** [comment]
Oh, that sounds like the GitHub API might need a personal auth token to not get rate limited – I don't see anything in the all-contributors-cli that mentions how to use an auth token though

**Comment by BeniCheni** [comment]
> Oh, that sounds like the GitHub API might need a personal auth token to not get rate limited – I don't see anything in the all-contributors-cli that mentions how to use an auth token though

Concur that all-contributors-cli doc doesn't not mention this API rate nuance, so it wasn't too helpful in the research. I could use #427 to move forward to triage whether it's something I could do with GitHub profile tocket settings or something "_deeper_". Will raise this topic in the next WG session.

**Pull request merged**
